image:
  repository: danielqsj/kafka-exporter
  tag: ""
  pullPolicy: IfNotPresent

command: []

imagePullSecrets: []

deploymentLabels: {}

global:
  imagePullSecrets: []

replicaCount: 1

kafkaServer:
  - kafka.g29-uat.svc:9092

kafkaBrokerVersion:

verbosity: 0

sarama:
  logEnabled: false

rbac:
  create: true
  pspEnabled: false

serviceAccount:
  create: true
  name:

env: []

service:
  type: ClusterIP
  port: 9308
  labels: {}
  annotations: {}
  nodePort: null
  loadBalancerIP: null

liveness:
  enabled: false
  probe:
    httpGet:
      path: /
      port: exporter-port

readiness:
  enabled: false
  probe:
    httpGet:
      path: /
      port: exporter-port

prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    apiVersion: "monitoring.coreos.com/v1"
    interval: "1m"
    additionalLabels:
      release: kube-prometheus-stack
    targetLabels: []
    relabelings: null
    metricRelabelings: null

podLabels: {}

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector:
  tier: app

# Annotations to attach to pod
annotations: {}

tolerations: []

affinity: {}

tls:
  enabled: false
  insecureSkipVerify: false
  serverName: ""

sasl:
  enabled: false
  handshake: true
  scram:
    enabled: false

  kerberos:
    enabled: false

server:
  tls:
    enabled: false
    mutualAuthEnabled: false

kafka:
  enabled: false

securityContext: {}

containerSecurityContext: {}
